### ISSUE TITLE
Missing generic implementation or helper

### ISSUE THREAD

**Issue by bill-myers** [ogxd/gxhash#10] opened 2023-11-17 18:46 UTC
The crate seems to be missing a non-arch specific implementation, which forces anyone using gxhash to select another hash and use cfg directives to choose between them (obviously releasing non-specialized crates that only work on x86-64 and arm64 is not acceptable).

If the user selecting another hash is desired, then all GxHash types should take the other hash as a generic parameter, for user convenience.

**Comment by ogxd** [comment] 2023-11-17 19:09
Yes you're right, it is important to provide a fallback. That's probably the 1st priority. Something can be done in the spirit of what is done for the crate `ahash`

**Comment by ogxd** [comment] 2023-12-23 20:13
Closing as duplicate of https://github.com/ogxd/gxhash/issues/47

**Closed by ogxd** 2023-12-23 20:13 UTC
Labels: compatibility
